### ISSUE TITLE
No artifacts being downloaded using latest VSTS 

### ISSUE THREAD

**Issue by Christoffleroux** [chamindac/vsts.release.task.download-artifacts#1]
Hi Im using the latest online version of VSTS

I have an on premis build agent that defines a single build producing multiple artifacts.  

The artifacts are published to an on premise file share.

When using the standard 'Download Atrifacts' task provided by VSTS all the artifacts are downloaded successfylle as expected. See the attacked log files.

When using the extension to download the same artifacts using the \* argument no artifacts where actualy downloaded after the task has run.  

If you look at the log file attacted the downloading of all the artifacts are being logged but the target folder is  empty.

Also when I specify only to download certain artifacts no artifacts are downloading to the target folder.

[Download Artifacts Log Files .zip](https://github.com/chamindac/vsts.release.task.download-artifacts/files/405129/Download.Artifacts.Log.Files.zip)

**Comment by chamindac** [comment]
Hi Christoffleroux,

I have found an issue when having spaces in build drop paths and in build definition names. Made few other issue fixes as well. A new enhancement added to support even downloading from sub paths within an artifact. I really appreciate if you could do a test on your server before I do a public release, to check, if your issues is fixed with this version. 1.1.10. After updating the extension please make sure to do a small change in you release definition and save it before doing a release. This is required since I have limited the input parameters to only one parameter now. vsix is attached.
Really appreciate your feedback given on this and helping me to fix an issue with the extension. Kindly verify and let me know if it works for you.
[chamindac.chamindac-vsts-release-task-download-artifacts-1.1.10.zip](https://github.com/chamindac/vsts.release.task.download-artifacts/files/405183/chamindac.chamindac-vsts-release-task-download-artifacts-1.1.10.zip)

**Comment by Christoffleroux** [comment]
Hi thanks for the response, really appreciate it. 

I’m using the online team services and have no idea how to test the attached extension.  Is there some way I can update the installed online version?

**Comment by chamindac** [comment]
Hi Christoffleroux,

I made it available for VSTS. Kindly check new version and let me know if your issue is resolved. (please make sure to do a small change in you release definition and save it before doing a release.)

**Comment by Christoffleroux** [comment]
Hi, It's working now thanks, downloading all the artifacts when specifyinf \* and downloading specific artifacts when specifying the artifac names.

Thanks allot.

Just one note, Microsoft intruduced a link artifact alias for the linked artifacts this week, I see that when the standard download artifacts task is running the artifacts gets downloaded into a folder with the alias name 'smddevelopment' and not the Build.DefinitionName the artifacts are linked to 'Smd (development)'.  Please see the diffrence in the log files I provided.  One was able to overcome this change using the desitaniton folder parameter the extention had in but now has been removed.  I suggest either use the artifact alias as the destination folder or include the destination folder parameter, or both if possible.

**Comment by chamindac** [comment]
Hi Christoffleroux,

Thanks for the confirmation of the fix and for the suggestion. Since, I want to keep the compatibility with TFS 2015.2.1 (on-premise TFS) I have re-enabled the parameter "Artifacts Destination", to facilitate the alias, path requirement. Once on-premise TFS (TFS vNext) is released with this "linked artifacts improvements", I will change the extension to use it.
![image](https://cloud.githubusercontent.com/assets/20109548/17470358/318c8fc8-5d59-11e6-8624-c27d401a33fa.png)
